# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###


POST http://127.0.0.1:8000/predict
Content-Type: application/json

{
    "type": "L",
    "air_temperature": 25.65,
    "process_temperature": 35.75,
    "rotational_speed": 1455.0,
    "torque": 41.3,
    "tool_wear": 208.0,
    "target": 1.0
}